apiVersion: v1
kind: Secret
metadata:
  name: cosign-pub
  namespace: flux-system
type: Opaque
stringData:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkAgu26dkUj9UcO0zoEpli4CD8B0p
    k+YPa1RlIz625eldAwx56argKN0jqdy82pfGor3qZBA++QWwlUrHH9VK7A==
    -----END PUBLIC KEY-----
