---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: librepod-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  valuesContent: |-
    # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
    dex:
      enabled: false

    configs:
      cm:
        timeout.reconciliation: 30s
      params:
        # Delegating TLS to traefik:
        server.insecure: true

      secret:
        # Bcrypt hashed admin password
        # Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
        # `htpasswd -nbBC 10 "" admin | tr -d ':\n' | sed 's/$2y/$2a/'`
        argocdServerAdminPassword: "$2a$10$QnA0qfPEMOWK7gxvcL/oLuExJT1mA4KpOY7ASutCBEVFl7.fVqrvq"

    server:
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22
      ingress:
        enabled: false

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd-apps
  namespace: librepod-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argocd-apps
  targetNamespace: argocd
  valuesContent: |-
    applications:
      - name: root-app
        namespace: argocd
        destination:
          server: https://kubernetes.default.svc
        ignoreDifferences:
          - group: argoproj.io
            jsonPointers:
              - /status
            kind: Application
        project: default
        sources:
          - repoURL: https://github.com/librepod/charts
            targetRevision: switch-to-argocd
            path: apps/argocd/librepod-system
          - repoURL: https://github.com/librepod/charts
            targetRevision: switch-to-argocd
            path: apps/argocd/librepod-apps
        syncPolicy:
          automated:
            allowEmpty: true
            prune: true
            selfHeal: true
