#!/usr/bin/env bash
# LibrePod appliance installer — run from the netboot installer image.
# Generates the device-owned flake, formats via disko, installs NixOS.
set -euo pipefail

MNT="${LIBREPOD_TARGET_MNT:-/mnt}"
WORKDIR="${LIBREPOD_WORKDIR:-}"
DISKO_BIN="${DISKO_BIN:-disko}"
NIXOS_INSTALL_BIN="${NIXOS_INSTALL_BIN:-nixos-install}"
NIX_BIN="${NIX_BIN:-nix}"
CURL_BIN="${CURL_BIN:-curl}"

usage() {
  echo "usage: librepod-install --device <hw-profile> --name <hostname>"
  echo "                      [--os-tag vX.Y.Z] [--identity FILE]"
  exit 1
}

DEVICE="" NAME="" TAG="" IDENTITY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --device) DEVICE="$2"; shift 2;;
    --name) NAME="$2"; shift 2;;
    --os-tag) TAG="$2"; shift 2;;
    --identity) IDENTITY="$2"; shift 2;;
    *) usage;;
  esac
done
[ -n "$DEVICE" ] && [ -n "$NAME" ] || usage
[ -n "$IDENTITY" ] || { echo "--identity is required (users/keys live there)"; exit 1; }

if [ -z "$TAG" ]; then
  TAG="$("$CURL_BIN" -fsSL https://api.github.com/repos/librepod/os/releases/latest \
    | jq -r .tag_name)" || { echo "could not resolve latest release; pass --os-tag"; exit 1; }
fi
[[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "invalid tag: $TAG"; exit 1; }

WORKDIR="${WORKDIR:-$(mktemp -d)}"
mkdir -p "$WORKDIR"

cat > "$WORKDIR/flake.nix" <<EOF
# Generated by librepod-install — owned by the device.
{
  # ponytail: the updater sed-targets this exact pin line; keep the format
  inputs.librepod.url = "github:librepod/os/${TAG}";
  outputs = { librepod, ... }: {
    nixosConfigurations.${NAME} = librepod.lib.mkDevice {
      name = "${NAME}";
      device = "${DEVICE}";
      modules = [ ./identity.nix ];
    };
  };
}
EOF
cp "$IDENTITY" "$WORKDIR/identity.nix"

# Resolve the tag to a lockfile now, so the installed device is fully pinned.
(cd "$WORKDIR" && "$NIX_BIN" --extra-experimental-features "nix-command flakes" \
  flake lock --accept-flake-config >/dev/null)

echo "==> partitioning + formatting via disko (DESTROYS the disk)"
"$DISKO_BIN" --flake "$WORKDIR#$NAME" --mode destroy,format,mount

echo "==> installing NixOS"
install -d -m 700 "$MNT/etc/nixos"
install -m 600 "$WORKDIR/identity.nix" "$MNT/etc/nixos/identity.nix"
install -m 644 "$WORKDIR/flake.nix" "$MNT/etc/nixos/flake.nix"
install -m 644 "$WORKDIR/flake.lock" "$MNT/etc/nixos/flake.lock"

"$NIXOS_INSTALL_BIN" --flake "$WORKDIR#$NAME" --no-root-passwd

echo "==> installed $NAME ($DEVICE, $TAG). Reboot into the device when ready."
