apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubeapps
  namespace: kube-system
spec:
  chart: kubeapps
  repo: "https://charts.bitnami.com/bitnami"
  targetNamespace: kube-system
  version: 7.7.2
  valuesContent: |-
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hostname: "apps.{{domain}}"
    postgresql:
      enabled: true
      replication:
        enabled: false
    apprepository:
      initialRepos:
        - name: cheeba-ryba
          url: https://cheeba-ryba.github.io/charts
