# Borgmatic backup module with FluxCD integration
#
# This module configures borgmatic for automated nightly backups of k3s PVC data.
# All PVCs are backed up by default; label `backup.librepod.dev/disabled=true` to skip.
# Borg's content-addressed storage enables per-PVC restore via path-based extraction
# without requiring separate backup jobs per PVC.
#
# Pre/post backup hooks suspend/resume HelmReleases and FluxCD Kustomizations,
# then scale K8s deployments for consistent snapshots.
# The hooks use borgmatic's `commands` system (not deprecated before_backup/after_backup).
#
# Post-backup resumes HelmReleases BEFORE Kustomizations to avoid a circular
# dependency: bootstrap Jobs (applied by Kustomizations) poll services deployed
# by HelmReleases. If HelmReleases are still suspended when the Job starts,
# the Job fails, the Kustomization fails, and the script exits before ever
# resuming HelmReleases. See post-backup.sh for the full SSA field-ownership
# explanation.
#
# Dynamic source directories:
#   A generate-sources script queries k8s for labeled PVCs, resolves their NFS paths
#   via the bound PV's spec.nfs.path, and writes them to /run/borgmatic/sources.yaml.
#   The base borgmatic config includes this file via <<: !include (deep merge).
#   Because pkgs.formats.yaml cannot produce the custom <<: !include YAML tag,
#   we use runCommand to prepend it to the generated config.
#
# To skip a PVC from backup:
#   kubectl label pvc <pvc-name> -n <namespace> backup.librepod.dev/disabled=true
#
# To restore a specific PVC:
#   borgmatic extract --archive latest --restore-path exports/k3s/<namespace>/<pvc-name>/

{
  config,
  pkgs,
  lib,
  ...
}:

let
  repoPath = "/media/USB DISK/borg-repo";
  mountPoint = "/media/USB DISK";

  ensureRepoScript = pkgs.writeShellApplication {
    name = "borgmatic-ensure-repo";
    runtimeInputs = with pkgs; [
      borgbackup
      util-linux
    ];
    text = ''
      # Soft fail if the backup drive isn't mounted (exit 75 = skip this repo gracefully)
      if ! findmnt '${mountPoint}' > /dev/null; then
        echo 'LOG:INFO Backup drive not mounted, skipping (soft failure)'
        exit 75
      fi

      # Auto-initialize the borg repository on first run
      if [ ! -f '${repoPath}/config' ]; then
        echo 'LOG:INFO Initializing borg repository at ${repoPath}'
        borg init --encryption=none '${repoPath}'
      fi
    '';
  };

  generateSourcesScript = pkgs.writeShellApplication {
    name = "borgmatic-generate-sources";
    runtimeInputs = with pkgs; [
      k3s
      jq
      coreutils
    ];
    text = builtins.readFile ./scripts/generate-sources.sh;
  };

  preBackupScript = pkgs.writeShellApplication {
    name = "borgmatic-pre-backup";
    runtimeInputs = with pkgs; [
      k3s
      fluxcd
      jq
      coreutils
    ];
    text = builtins.readFile ./scripts/pre-backup.sh;
  };

  postBackupScript = pkgs.writeShellApplication {
    name = "borgmatic-post-backup";
    runtimeInputs = with pkgs; [
      k3s
      fluxcd
      coreutils
    ];
    text = builtins.readFile ./scripts/post-backup.sh;
  };

  # Generate structured borgmatic config, then prepend the <<: !include directive.
  # pkgs.formats.yaml cannot produce custom YAML tags (like !include) or unquoted
  # merge keys (<<), so we concatenate: raw include line + generated YAML body.
  borgmaticConfig =
    let
      rawConfig = (pkgs.formats.yaml { }).generate "borgmatic-raw.yaml" {
        repositories = [
          {
            path = repoPath;
            label = "local";
          }
        ];
        compression = "zstd,3";
        keep_daily = 7;
        keep_weekly = 4;
        keep_monthly = 12;
        commands = [
          {
            before = "repository";
            run = [ "${ensureRepoScript}/bin/borgmatic-ensure-repo" ];
          }
          {
            before = "configuration";
            when = [ "create" ];
            run = [ "${preBackupScript}/bin/borgmatic-pre-backup" ];
          }
          {
            after = "configuration";
            when = [ "create" ];
            states = [
              "finish"
              "fail"
            ];
            run = [ "${postBackupScript}/bin/borgmatic-post-backup" ];
          }
        ];
      };
    in
    pkgs.runCommand "borgmatic-config.yaml" { } ''
      echo '<<: !include /run/borgmatic/sources.yaml' > $out
      cat ${rawConfig} >> $out
    '';
in
{
  # Make backup scripts available system-wide
  environment.systemPackages = [
    generateSourcesScript
    preBackupScript
    postBackupScript
  ];

  # Borgmatic service configuration
  services.borgmatic = {
    enable = true;
    settings = { };
  };

  # Custom borgmatic config with <<: !include for dynamic source directories.
  # Overrides the empty config generated by services.borgmatic.settings.
  environment.etc."borgmatic/config.yaml".source = lib.mkForce borgmaticConfig;

  # Override timer schedule (default from upstream package is hourly)
  systemd.timers.borgmatic.timerConfig = {
    OnCalendar = "*-*-* 03:15:00";
    Persistent = true;
  };

  # Ensure borgmatic runs after k3s is ready, and generate dynamic sources before backup
  systemd.services.borgmatic = {
    wants = [
      "k3s.service"
      "network-online.target"
    ];
    after = [
      "k3s.service"
      "network-online.target"
    ];
    serviceConfig.ExecStartPre = [
      "${pkgs.coreutils}/bin/mkdir -p /run/borgmatic"
      "${generateSourcesScript}/bin/borgmatic-generate-sources"
    ];
  };
}
