---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: forecastle
  namespace: librepod-system
spec:
  chart: "https://github.com/librepod/charts/releases/download/forecastle-v1.0.113/forecastle-v1.0.113.tgz"
  targetNamespace: librepod-system
  valuesContent: |-
    forecastle:
      namespace: kube-system
      config:
        namespaceSelector:
          matchNames:
            - default
            - librepod-system
        headerBackground: "#ffc34d"
        headerForeground: null
        title: LibrePod
        instanceName: null
        customApps: {}
        crdEnabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: forecastle
  namespace: librepod-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{domain}}`)
      services:
      - name: forecastle
        passHostHeader: true
        port: 80
