apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hajimari
  namespace: kube-system
spec:
  chart: "https://github.com/librepod/charts/releases/download/hajimari-0.1.3/hajimari-0.1.3.tgz"
  targetNamespace: kube-system
  valuesContent: |-
    hajimari:
      customApps: []
      groups: []
      namespaceSelector:
        matchNames:
          - kube-system
    serviceAccount:
      create: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      paths:
        - /
      hosts:
        - host: "{{domain}}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: "{{domain}}-ingress-tls"
          hosts:
            - "{{domain}}"
