apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wg-easy
  namespace: librepod-system
spec:
  chart: "https://github.com/librepod/charts/releases/download/wg-easy-1.3.1/wg-easy-1.3.1.tgz"
  targetNamespace: librepod-system
  valuesContent: |-
    hostIP: "{{hostIP}}"
